// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vtb_kyber_top.h for the primary calling header

#ifndef VERILATED_VTB_KYBER_TOP___024ROOT_H_
#define VERILATED_VTB_KYBER_TOP___024ROOT_H_  // guard

#include "verilated.h"
#include "verilated_timing.h"


class Vtb_kyber_top__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vtb_kyber_top___024root final {
  public:

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        CData/*0:0*/ tb_kyber_top__DOT__clk;
        CData/*0:0*/ tb_kyber_top__DOT__rst;
        CData/*0:0*/ tb_kyber_top__DOT__start;
        CData/*1:0*/ tb_kyber_top__DOT__opcode;
        CData/*1:0*/ tb_kyber_top__DOT__mode_k;
        CData/*0:0*/ tb_kyber_top__DOT__done;
        CData/*0:0*/ tb_kyber_top__DOT__busy;
        CData/*0:0*/ tb_kyber_top__DOT__ext_we;
        CData/*0:0*/ tb_kyber_top__DOT__ext_re;
        CData/*7:0*/ tb_kyber_top__DOT__print_hex_block__Vstatic__b;
        CData/*7:0*/ tb_kyber_top__DOT__uut__DOT____Vlvbound_h19da1bf1__2;
        CData/*7:0*/ tb_kyber_top__DOT__uut__DOT____Vlvbound_h593c9377__1;
        CData/*7:0*/ tb_kyber_top__DOT__uut__DOT____Vlvbound_h593c9377__0;
        CData/*7:0*/ tb_kyber_top__DOT__uut__DOT____Vlvbound_h19da1bf1__1;
        CData/*7:0*/ tb_kyber_top__DOT__uut__DOT____Vlvbound_h19da1bf1__0;
        CData/*0:0*/ tb_kyber_top__DOT__uut__DOT__dec_ct_match;
        CData/*0:0*/ tb_kyber_top__DOT__uut__DOT__dec_reenc_mode;
        CData/*0:0*/ tb_kyber_top__DOT__uut__DOT__enc_kdf_ready;
        CData/*0:0*/ tb_kyber_top__DOT__uut__DOT__dec_kdf_ready;
        CData/*0:0*/ tb_kyber_top__DOT__uut__DOT__pwma_sp_from_scratch;
        CData/*0:0*/ tb_kyber_top__DOT__uut__DOT__pwma_use_tomont;
        CData/*1:0*/ tb_kyber_top__DOT__uut__DOT__enc_noise_kind;
        CData/*1:0*/ tb_kyber_top__DOT__uut__DOT__enc_ntt_phase;
        CData/*7:0*/ tb_kyber_top__DOT__uut__DOT__state;
        CData/*2:0*/ tb_kyber_top__DOT__uut__DOT__loop_i;
        CData/*2:0*/ tb_kyber_top__DOT__uut__DOT__loop_j;
        CData/*3:0*/ tb_kyber_top__DOT__uut__DOT__dec_phase;
        CData/*0:0*/ tb_kyber_top__DOT__uut__DOT__ntt_dec_intt_gs_en;
        CData/*0:0*/ tb_kyber_top__DOT__uut__DOT__hpk_we;
        CData/*7:0*/ tb_kyber_top__DOT__uut__DOT__hpk_din;
        CData/*7:0*/ tb_kyber_top__DOT__uut__DOT__hpk_dout;
        CData/*0:0*/ tb_kyber_top__DOT__uut__DOT__ct_we;
        CData/*7:0*/ tb_kyber_top__DOT__uut__DOT__ct_din;
        CData/*7:0*/ tb_kyber_top__DOT__uut__DOT__ct_dout;
        CData/*0:0*/ tb_kyber_top__DOT__uut__DOT__ct_dec_we;
        CData/*7:0*/ tb_kyber_top__DOT__uut__DOT__ct_dec_din;
        CData/*7:0*/ tb_kyber_top__DOT__uut__DOT__ct_dec_dout;
        CData/*0:0*/ tb_kyber_top__DOT__uut__DOT__ct_reenc_we;
        CData/*7:0*/ tb_kyber_top__DOT__uut__DOT__ct_reenc_din;
        CData/*7:0*/ tb_kyber_top__DOT__uut__DOT__ct_reenc_dout;
        CData/*0:0*/ tb_kyber_top__DOT__uut__DOT__hash_start;
        CData/*2:0*/ tb_kyber_top__DOT__uut__DOT__hash_cmd;
        CData/*7:0*/ tb_kyber_top__DOT__uut__DOT__hash_bytes;
        CData/*0:0*/ tb_kyber_top__DOT__uut__DOT__hash_prf_eta3;
        CData/*0:0*/ tb_kyber_top__DOT__uut__DOT__hash_stream_en;
        CData/*0:0*/ tb_kyber_top__DOT__uut__DOT__hash_stream_valid;
        CData/*0:0*/ tb_kyber_top__DOT__uut__DOT__hash_stream_last;
        CData/*7:0*/ tb_kyber_top__DOT__uut__DOT__hash_stream_bytes;
        CData/*0:0*/ tb_kyber_top__DOT__uut__DOT__hash_done;
        CData/*0:0*/ tb_kyber_top__DOT__uut__DOT__cbd_start;
        CData/*0:0*/ tb_kyber_top__DOT__uut__DOT__cbd_eta3_mode;
        CData/*0:0*/ tb_kyber_top__DOT__uut__DOT__cbd_we;
        CData/*0:0*/ tb_kyber_top__DOT__uut__DOT__cbd_done;
        CData/*0:0*/ tb_kyber_top__DOT__uut__DOT__gm_start;
        CData/*0:0*/ tb_kyber_top__DOT__uut__DOT__gm_transposed;
        CData/*0:0*/ tb_kyber_top__DOT__uut__DOT__gm_we;
        CData/*0:0*/ tb_kyber_top__DOT__uut__DOT__gm_done;
        CData/*0:0*/ tb_kyber_top__DOT__uut__DOT__ntt_start;
        CData/*0:0*/ tb_kyber_top__DOT__uut__DOT__ntt_mode;
        CData/*0:0*/ tb_kyber_top__DOT__uut__DOT__ntt_done;
        CData/*0:0*/ tb_kyber_top__DOT__uut__DOT__ntt_ext_we;
        CData/*7:0*/ tb_kyber_top__DOT__uut__DOT__ntt_ext_addr;
        CData/*0:0*/ tb_kyber_top__DOT__uut__DOT__pwma_start;
        CData/*0:0*/ tb_kyber_top__DOT__uut__DOT__pwma_done;
    };
    struct {
        CData/*7:0*/ tb_kyber_top__DOT__uut__DOT__pwma_ram0_addr;
        CData/*7:0*/ tb_kyber_top__DOT__uut__DOT__pwma_ram1_addr;
        CData/*0:0*/ tb_kyber_top__DOT__uut__DOT__pwma_ram1_we;
        CData/*6:0*/ tb_kyber_top__DOT__uut__DOT__pwma_zeta_addr;
        CData/*0:0*/ tb_kyber_top__DOT__uut__DOT__cmp_start;
        CData/*0:0*/ tb_kyber_top__DOT__uut__DOT__cmp_done;
        CData/*0:0*/ tb_kyber_top__DOT__uut__DOT__cmp_not_equal;
        CData/*0:0*/ tb_kyber_top__DOT__uut__DOT__comp_op;
        CData/*3:0*/ tb_kyber_top__DOT__uut__DOT__comp_d;
        CData/*2:0*/ tb_kyber_top__DOT__uut__DOT__mux_sel;
        CData/*2:0*/ tb_kyber_top__DOT__uut__DOT__ntt_mux_sel;
        CData/*0:0*/ tb_kyber_top__DOT__uut__DOT__fsm_we_a;
        CData/*0:0*/ tb_kyber_top__DOT__uut__DOT__fsm_we_b;
        CData/*0:0*/ tb_kyber_top__DOT__uut__DOT__fsm_ntt_we;
        CData/*7:0*/ tb_kyber_top__DOT__uut__DOT__fsm_ntt_addr;
        CData/*3:0*/ tb_kyber_top__DOT__uut__DOT__dec_slot_idx;
        CData/*0:0*/ tb_kyber_top__DOT__uut__DOT__dec_unpack_group_valid;
        CData/*2:0*/ tb_kyber_top__DOT__uut__DOT__dec_j_idx;
        CData/*2:0*/ tb_kyber_top__DOT__uut__DOT__dec_j_work;
        CData/*2:0*/ tb_kyber_top__DOT__uut__DOT__dec_codec_op_w;
        CData/*2:0*/ tb_kyber_top__DOT__uut__DOT__pwma_sp_poly_idx;
        CData/*0:0*/ tb_kyber_top__DOT__uut__DOT__scratch_we_a;
        CData/*0:0*/ tb_kyber_top__DOT__uut__DOT__scratch_we_b;
        CData/*0:0*/ tb_kyber_top__DOT__uut__DOT__a_cache_we_fsm;
        CData/*0:0*/ tb_kyber_top__DOT__uut__DOT__scratch_pwma_sel;
        CData/*0:0*/ tb_kyber_top__DOT__uut__DOT__ct_pack_start;
        CData/*0:0*/ tb_kyber_top__DOT__uut__DOT__ct_pack_done;
        CData/*7:0*/ tb_kyber_top__DOT__uut__DOT__ct_pack_v_addr;
        CData/*0:0*/ tb_kyber_top__DOT__uut__DOT__ct_pack_ext_we;
        CData/*0:0*/ tb_kyber_top__DOT__uut__DOT__hash_sent;
        CData/*0:0*/ tb_kyber_top__DOT__uut__DOT__cbd_sent;
        CData/*0:0*/ tb_kyber_top__DOT__uut__DOT__ntt_sent;
        CData/*0:0*/ tb_kyber_top__DOT__uut__DOT__pwma_sent;
        CData/*0:0*/ tb_kyber_top__DOT__uut__DOT__cmp_sent;
        CData/*0:0*/ tb_kyber_top__DOT__uut__DOT__gm_sent;
        CData/*0:0*/ tb_kyber_top__DOT__uut__DOT__ct_pack_sent;
        CData/*1:0*/ tb_kyber_top__DOT__uut__DOT__pack_phase;
        CData/*2:0*/ tb_kyber_top__DOT__uut__DOT__pack_poly;
        CData/*7:0*/ tb_kyber_top__DOT__uut__DOT__pack_pair;
        CData/*2:0*/ tb_kyber_top__DOT__uut__DOT__pack_step;
        CData/*7:0*/ tb_kyber_top__DOT__uut__DOT__pack_b0;
        CData/*7:0*/ tb_kyber_top__DOT__uut__DOT__pack_b1;
        CData/*7:0*/ tb_kyber_top__DOT__uut__DOT__pack_b2;
        CData/*0:0*/ tb_kyber_top__DOT__uut__DOT__dec_sk_reload_done;
        CData/*2:0*/ tb_kyber_top__DOT__uut__DOT__dec_sk_poly;
        CData/*7:0*/ tb_kyber_top__DOT__uut__DOT__dec_sk_pair;
        CData/*2:0*/ tb_kyber_top__DOT__uut__DOT__dec_sk_step;
        CData/*7:0*/ tb_kyber_top__DOT__uut__DOT__dec_sk_b0;
        CData/*7:0*/ tb_kyber_top__DOT__uut__DOT__dec_sk_b1;
        CData/*7:0*/ tb_kyber_top__DOT__uut__DOT__dec_sk_b2;
        CData/*0:0*/ tb_kyber_top__DOT__uut__DOT__hash_fetching;
        CData/*0:0*/ tb_kyber_top__DOT__uut__DOT__fetch_wait;
        CData/*7:0*/ tb_kyber_top__DOT__uut__DOT__fetch_cnt;
        CData/*0:0*/ tb_kyber_top__DOT__uut__DOT__dec_fetch_done;
        CData/*7:0*/ tb_kyber_top__DOT__uut__DOT__mb;
        CData/*7:0*/ tb_kyber_top__DOT__uut__DOT__bytev;
        CData/*7:0*/ tb_kyber_top__DOT__uut__DOT__first_in;
        CData/*7:0*/ tb_kyber_top__DOT__uut__DOT__first_re;
        CData/*4:0*/ tb_kyber_top__DOT__uut__DOT__mbyte_idx;
        CData/*4:0*/ tb_kyber_top__DOT__uut__DOT__mbyte_idx_dec;
        CData/*2:0*/ tb_kyber_top__DOT__uut__DOT__mb_idx;
        CData/*0:0*/ tb_kyber_top__DOT__uut__DOT__mbit;
        CData/*0:0*/ tb_kyber_top__DOT__uut__DOT__all_eq;
        CData/*0:0*/ tb_kyber_top__DOT__uut__DOT__u_hash__DOT__stream_ack;
    };
    struct {
        CData/*2:0*/ tb_kyber_top__DOT__uut__DOT__u_hash__DOT__out_len_type;
        CData/*0:0*/ tb_kyber_top__DOT__uut__DOT__u_hash__DOT__mode;
        CData/*0:0*/ tb_kyber_top__DOT__uut__DOT__u_hash__DOT__is_sha3;
        CData/*0:0*/ tb_kyber_top__DOT__uut__DOT__u_hash__DOT__u_shake__DOT__i_valid;
        CData/*0:0*/ tb_kyber_top__DOT__uut__DOT__u_hash__DOT__u_shake__DOT__i_last;
        CData/*7:0*/ tb_kyber_top__DOT__uut__DOT__u_hash__DOT__u_shake__DOT__eff_len;
        CData/*0:0*/ tb_kyber_top__DOT__uut__DOT__u_hash__DOT__u_shake__DOT__i_ack;
        CData/*0:0*/ tb_kyber_top__DOT__uut__DOT__u_hash__DOT__u_shake__DOT__sponge_inst__DOT____Vlvbound_h258c997c__0;
        CData/*7:0*/ tb_kyber_top__DOT__uut__DOT__u_hash__DOT__u_shake__DOT__sponge_inst__DOT____Vlvbound_h4713971b__1;
        CData/*7:0*/ tb_kyber_top__DOT__uut__DOT__u_hash__DOT__u_shake__DOT__sponge_inst__DOT____Vlvbound_h4713971b__0;
        CData/*7:0*/ tb_kyber_top__DOT__uut__DOT__u_hash__DOT__u_shake__DOT__sponge_inst__DOT____Vlvbound_h5f820b96__0;
        CData/*3:0*/ tb_kyber_top__DOT__uut__DOT__u_hash__DOT__u_shake__DOT__sponge_inst__DOT__state;
        CData/*7:0*/ tb_kyber_top__DOT__uut__DOT__u_hash__DOT__u_shake__DOT__sponge_inst__DOT__beat_len;
        CData/*0:0*/ tb_kyber_top__DOT__uut__DOT__u_hash__DOT__u_shake__DOT__sponge_inst__DOT__beat_last;
        CData/*0:0*/ tb_kyber_top__DOT__uut__DOT__u_hash__DOT__u_shake__DOT__sponge_inst__DOT__final_full_block;
        CData/*0:0*/ tb_kyber_top__DOT__uut__DOT__u_hash__DOT__u_shake__DOT__sponge_inst__DOT__saved_mode;
        CData/*0:0*/ tb_kyber_top__DOT__uut__DOT__u_hash__DOT__u_shake__DOT__sponge_inst__DOT__saved_is_sha3;
        CData/*2:0*/ tb_kyber_top__DOT__uut__DOT__u_hash__DOT__u_shake__DOT__sponge_inst__DOT__saved_out_len_type;
        CData/*0:0*/ tb_kyber_top__DOT__uut__DOT__u_hash__DOT__u_shake__DOT__sponge_inst__DOT__f_start;
        CData/*0:0*/ tb_kyber_top__DOT__uut__DOT__u_hash__DOT__u_shake__DOT__sponge_inst__DOT__f_done;
        CData/*1:0*/ tb_kyber_top__DOT__uut__DOT__u_hash__DOT__u_shake__DOT__sponge_inst__DOT__f_inst__DOT__state;
        CData/*4:0*/ tb_kyber_top__DOT__uut__DOT__u_hash__DOT__u_shake__DOT__sponge_inst__DOT__f_inst__DOT__round_cnt;
        CData/*1:0*/ tb_kyber_top__DOT__uut__DOT__u_cbd__DOT__state;
        CData/*0:0*/ tb_kyber_top__DOT__uut__DOT__u_cbd__DOT__saved_eta3;
        CData/*0:0*/ tb_kyber_top__DOT__uut__DOT__u_gm__DOT__xof_absorb_start;
        CData/*0:0*/ tb_kyber_top__DOT__uut__DOT__u_gm__DOT__xof_squeeze_next;
        CData/*0:0*/ tb_kyber_top__DOT__uut__DOT__u_gm__DOT__xof_squeeze_valid;
        CData/*2:0*/ tb_kyber_top__DOT__uut__DOT__u_gm__DOT__loop_i;
        CData/*2:0*/ tb_kyber_top__DOT__uut__DOT__u_gm__DOT__loop_j;
        CData/*2:0*/ tb_kyber_top__DOT__uut__DOT__u_gm__DOT__k_val;
        CData/*2:0*/ tb_kyber_top__DOT__uut__DOT__u_gm__DOT__state;
        CData/*1:0*/ tb_kyber_top__DOT__uut__DOT__u_gm__DOT__u_xof__DOT__state;
        CData/*0:0*/ tb_kyber_top__DOT__uut__DOT__u_gm__DOT__u_xof__DOT__f_start;
        CData/*0:0*/ tb_kyber_top__DOT__uut__DOT__u_gm__DOT__u_xof__DOT__f_done;
        CData/*1:0*/ tb_kyber_top__DOT__uut__DOT__u_gm__DOT__u_xof__DOT__keccak_inst__DOT__state;
        CData/*4:0*/ tb_kyber_top__DOT__uut__DOT__u_gm__DOT__u_xof__DOT__keccak_inst__DOT__round_cnt;
        CData/*2:0*/ tb_kyber_top__DOT__uut__DOT__u_ntt__DOT__state;
        CData/*2:0*/ tb_kyber_top__DOT__uut__DOT__u_ntt__DOT__stage;
        CData/*7:0*/ tb_kyber_top__DOT__uut__DOT__u_ntt__DOT__cnt;
        CData/*1:0*/ tb_kyber_top__DOT__uut__DOT__u_ntt__DOT__warm_cnt;
        CData/*3:0*/ tb_kyber_top__DOT__uut__DOT__u_ntt__DOT__dbg_tag_id;
        CData/*0:0*/ tb_kyber_top__DOT__uut__DOT__u_ntt__DOT__last_write_ram;
        CData/*0:0*/ tb_kyber_top__DOT__uut__DOT__u_ntt__DOT__u_addr_gen__DOT__inv_gs_en;
        CData/*7:0*/ tb_kyber_top__DOT__uut__DOT__u_ntt__DOT__u_addr_gen__DOT__addr_a;
        CData/*7:0*/ tb_kyber_top__DOT__uut__DOT__u_ntt__DOT__u_addr_gen__DOT__addr_b;
        CData/*7:0*/ tb_kyber_top__DOT__uut__DOT__u_ntt__DOT__u_addr_gen__DOT__group;
        CData/*2:0*/ tb_kyber_top__DOT__uut__DOT__u_ntt__DOT__u_addr_gen__DOT__stage_eff;
        CData/*0:0*/ tb_kyber_top__DOT__uut__DOT__u_ntt__DOT__u_butterfly__DOT__s1_mode;
        CData/*0:0*/ tb_kyber_top__DOT__uut__DOT__u_ntt__DOT__u_ram0__DOT__we_a;
        CData/*7:0*/ tb_kyber_top__DOT__uut__DOT__u_ntt__DOT__u_ram0__DOT__addr_a;
        CData/*0:0*/ tb_kyber_top__DOT__uut__DOT__u_ntt__DOT__u_ram0__DOT__we_b;
        CData/*7:0*/ tb_kyber_top__DOT__uut__DOT__u_ntt__DOT__u_ram0__DOT__addr_b;
        CData/*0:0*/ tb_kyber_top__DOT__uut__DOT__u_ntt__DOT__u_ram1__DOT__we_a;
        CData/*7:0*/ tb_kyber_top__DOT__uut__DOT__u_ntt__DOT__u_ram1__DOT__addr_a;
        CData/*7:0*/ tb_kyber_top__DOT__uut__DOT__u_ntt__DOT__u_ram1__DOT__addr_b;
        CData/*3:0*/ tb_kyber_top__DOT__uut__DOT__u_pwma__DOT__state;
        CData/*7:0*/ tb_kyber_top__DOT__uut__DOT__u_pwma__DOT__cnt;
        CData/*7:0*/ tb_kyber_top__DOT__uut__DOT__u_pwma__DOT__pair_hold;
        CData/*7:0*/ tb_kyber_top__DOT__uut__DOT__u_pwma__DOT__s1_pair;
        CData/*1:0*/ tb_kyber_top__DOT__uut__DOT__u_cmp__DOT__state;
        CData/*0:0*/ tb_kyber_top__DOT__uut__DOT__u_cmp__DOT__diff_accumulator;
        CData/*3:0*/ tb_kyber_top__DOT__uut__DOT__u_ct_pack__DOT__state;
        CData/*3:0*/ tb_kyber_top__DOT__uut__DOT__u_ct_pack__DOT__cap_idx;
        CData/*3:0*/ tb_kyber_top__DOT__uut__DOT__u_ct_pack__DOT__wr_idx;
    };
    struct {
        CData/*1:0*/ tb_kyber_top__DOT__uut__DOT__u_ct_pack__DOT__wait_u;
        CData/*1:0*/ tb_kyber_top__DOT__uut__DOT__u_ct_pack__DOT__wait_v;
        CData/*2:0*/ tb_kyber_top__DOT__uut__DOT__u_ct_pack__DOT__codec_op;
        CData/*7:0*/ tb_kyber_top__DOT__uut__DOT__u_ct_pack__DOT__u_codec__DOT__b0;
        CData/*7:0*/ tb_kyber_top__DOT__uut__DOT__u_ct_pack__DOT__u_codec__DOT__b1;
        CData/*7:0*/ tb_kyber_top__DOT__uut__DOT__u_ct_pack__DOT__u_codec__DOT__b2;
        CData/*7:0*/ tb_kyber_top__DOT__uut__DOT__u_ct_pack__DOT__u_codec__DOT__b3;
        CData/*7:0*/ tb_kyber_top__DOT__uut__DOT__u_ct_pack__DOT__u_codec__DOT__b4;
        CData/*7:0*/ tb_kyber_top__DOT__uut__DOT__u_dec_codec__DOT__b0;
        CData/*7:0*/ tb_kyber_top__DOT__uut__DOT__u_dec_codec__DOT__b1;
        CData/*7:0*/ tb_kyber_top__DOT__uut__DOT__u_dec_codec__DOT__b2;
        CData/*7:0*/ tb_kyber_top__DOT__uut__DOT__u_dec_codec__DOT__b3;
        CData/*7:0*/ tb_kyber_top__DOT__uut__DOT__u_dec_codec__DOT__b4;
        CData/*0:0*/ __Vdly__tb_kyber_top__DOT__uut__DOT__u_hash__DOT__u_shake__DOT__sponge_inst__DOT__f_start;
        CData/*1:0*/ __Vdly__tb_kyber_top__DOT__uut__DOT__u_hash__DOT__u_shake__DOT__sponge_inst__DOT__f_inst__DOT__state;
        CData/*4:0*/ __Vdly__tb_kyber_top__DOT__uut__DOT__u_hash__DOT__u_shake__DOT__sponge_inst__DOT__f_inst__DOT__round_cnt;
        CData/*0:0*/ __VstlFirstIteration;
        CData/*0:0*/ __VstlPhaseResult;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tb_kyber_top__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tb_kyber_top__DOT__done__0;
        CData/*0:0*/ __VactPhaseResult;
        CData/*0:0*/ __VinactPhaseResult;
        CData/*0:0*/ __VnbaPhaseResult;
        SData/*15:0*/ tb_kyber_top__DOT__uut__DOT____VlemCall_8__barrett_reduce_q;
        SData/*11:0*/ tb_kyber_top__DOT__uut__DOT__dma_cnt;
        SData/*10:0*/ tb_kyber_top__DOT__uut__DOT__hpk_addr_a;
        SData/*10:0*/ tb_kyber_top__DOT__uut__DOT__hpk_addr_b;
        SData/*10:0*/ tb_kyber_top__DOT__uut__DOT__ct_addr_a;
        SData/*10:0*/ tb_kyber_top__DOT__uut__DOT__ct_addr_b;
        SData/*10:0*/ tb_kyber_top__DOT__uut__DOT__ct_dec_addr_a;
        SData/*10:0*/ tb_kyber_top__DOT__uut__DOT__ct_dec_addr_b;
        SData/*10:0*/ tb_kyber_top__DOT__uut__DOT__ct_reenc_addr_a;
        SData/*10:0*/ tb_kyber_top__DOT__uut__DOT__ct_reenc_addr_b;
        SData/*11:0*/ tb_kyber_top__DOT__uut__DOT__base_v;
        SData/*10:0*/ tb_kyber_top__DOT__uut__DOT__cbd_base_addr;
        SData/*10:0*/ tb_kyber_top__DOT__uut__DOT__cbd_ram_addr;
        SData/*15:0*/ tb_kyber_top__DOT__uut__DOT__cbd_poly_out;
        SData/*11:0*/ tb_kyber_top__DOT__uut__DOT__gm_ram_addr;
        SData/*15:0*/ tb_kyber_top__DOT__uut__DOT__gm_ram_din;
        SData/*15:0*/ tb_kyber_top__DOT__uut__DOT__ntt_ext_din;
        SData/*15:0*/ tb_kyber_top__DOT__uut__DOT__ntt_ext_dout;
        SData/*15:0*/ tb_kyber_top__DOT__uut__DOT__ntt_ext_dout_b;
        SData/*15:0*/ tb_kyber_top__DOT__uut__DOT__pwma_zeta_real;
        SData/*10:0*/ tb_kyber_top__DOT__uut__DOT__cmp_len;
        SData/*10:0*/ tb_kyber_top__DOT__uut__DOT__cmp_addr_c;
        SData/*10:0*/ tb_kyber_top__DOT__uut__DOT__cmp_addr_c_prime;
        SData/*11:0*/ tb_kyber_top__DOT__uut__DOT__fsm_addr_a;
        SData/*11:0*/ tb_kyber_top__DOT__uut__DOT__fsm_addr_b;
        SData/*15:0*/ tb_kyber_top__DOT__uut__DOT__fsm_din_a;
        SData/*15:0*/ tb_kyber_top__DOT__uut__DOT__fsm_din_b;
        SData/*15:0*/ tb_kyber_top__DOT__uut__DOT__fsm_ntt_din;
        SData/*11:0*/ tb_kyber_top__DOT__uut__DOT__pwma_acc_base;
        SData/*15:0*/ tb_kyber_top__DOT__uut__DOT__dbg_pwma_u_pair_cnt;
        SData/*15:0*/ tb_kyber_top__DOT__uut__DOT__dbg_pwma_v_pair_cnt;
        SData/*15:0*/ tb_kyber_top__DOT__uut__DOT__dbg_pwma_dec_pair_cnt;
        SData/*9:0*/ tb_kyber_top__DOT__uut__DOT__dec_group_idx;
        SData/*11:0*/ tb_kyber_top__DOT__uut__DOT__ct_cap_idx;
        SData/*15:0*/ tb_kyber_top__DOT__uut__DOT__add_main_d1;
        SData/*15:0*/ tb_kyber_top__DOT__uut__DOT__add_main_d2;
        SData/*15:0*/ tb_kyber_top__DOT__uut__DOT__add_main_d3;
        SData/*15:0*/ tb_kyber_top__DOT__uut__DOT__add_main_d4;
        SData/*11:0*/ tb_kyber_top__DOT__uut__DOT__scratch_addr_a;
        SData/*11:0*/ tb_kyber_top__DOT__uut__DOT__scratch_addr_b;
        SData/*15:0*/ tb_kyber_top__DOT__uut__DOT__scratch_din_a;
    };
    struct {
        SData/*15:0*/ tb_kyber_top__DOT__uut__DOT__scratch_din_b;
        SData/*11:0*/ tb_kyber_top__DOT__uut__DOT__a_cache_addr_fsm;
        SData/*15:0*/ tb_kyber_top__DOT__uut__DOT__a_cache_din_fsm;
        SData/*11:0*/ tb_kyber_top__DOT__uut__DOT__addr_a;
        SData/*11:0*/ tb_kyber_top__DOT__uut__DOT__addr_b;
        SData/*15:0*/ tb_kyber_top__DOT__uut__DOT__dout_a;
        SData/*15:0*/ tb_kyber_top__DOT__uut__DOT__dout_b;
        SData/*15:0*/ tb_kyber_top__DOT__uut__DOT__a_cache_dout_a;
        SData/*15:0*/ tb_kyber_top__DOT__uut__DOT__a_cache_dout_b;
        SData/*15:0*/ tb_kyber_top__DOT__uut__DOT__scratch_dout_a;
        SData/*15:0*/ tb_kyber_top__DOT__uut__DOT__scratch_dout_b;
        SData/*11:0*/ tb_kyber_top__DOT__uut__DOT__pwma_sp_addr_even;
        SData/*11:0*/ tb_kyber_top__DOT__uut__DOT__scratch_addr_a_mux;
        SData/*11:0*/ tb_kyber_top__DOT__uut__DOT__scratch_addr_b_mux;
        SData/*10:0*/ tb_kyber_top__DOT__uut__DOT__ct_pack_u_addr;
        SData/*11:0*/ tb_kyber_top__DOT__uut__DOT__a_cache_addr_even;
        SData/*15:0*/ tb_kyber_top__DOT__uut__DOT__pack_c0;
        SData/*15:0*/ tb_kyber_top__DOT__uut__DOT__pack_c1;
        SData/*15:0*/ tb_kyber_top__DOT__uut__DOT__dec_sk_c0;
        SData/*15:0*/ tb_kyber_top__DOT__uut__DOT__dec_sk_c1;
        SData/*11:0*/ tb_kyber_top__DOT__uut__DOT__rem12;
        SData/*11:0*/ tb_kyber_top__DOT__uut__DOT__rem12b;
        SData/*15:0*/ tb_kyber_top__DOT__uut__DOT__c0s;
        SData/*15:0*/ tb_kyber_top__DOT__uut__DOT__c1s;
        SData/*11:0*/ tb_kyber_top__DOT__uut__DOT__c0n;
        SData/*11:0*/ tb_kyber_top__DOT__uut__DOT__c1n;
        SData/*11:0*/ tb_kyber_top__DOT__uut__DOT__u_pair_base12;
        SData/*11:0*/ tb_kyber_top__DOT__uut__DOT__u_pair_base_b12;
        SData/*11:0*/ tb_kyber_top__DOT__uut__DOT__u_even_idx12;
        SData/*11:0*/ tb_kyber_top__DOT__uut__DOT__u_odd_idx12;
        SData/*11:0*/ tb_kyber_top__DOT__uut__DOT__u_global_even_idx12;
        SData/*11:0*/ tb_kyber_top__DOT__uut__DOT__u_global_odd_idx12;
        SData/*11:0*/ tb_kyber_top__DOT__uut__DOT__u_cand_off2_idx12;
        SData/*11:0*/ tb_kyber_top__DOT__uut__DOT__u_cand_off3_idx12;
        SData/*11:0*/ tb_kyber_top__DOT__uut__DOT__v_pair_base12;
        SData/*11:0*/ tb_kyber_top__DOT__uut__DOT__v_pair_base_b12;
        SData/*11:0*/ tb_kyber_top__DOT__uut__DOT__v_even_idx12;
        SData/*11:0*/ tb_kyber_top__DOT__uut__DOT__v_odd_idx12;
        SData/*11:0*/ tb_kyber_top__DOT__uut__DOT__v_cand_off2_idx12;
        SData/*11:0*/ tb_kyber_top__DOT__uut__DOT__v_cand_off3_idx12;
        SData/*11:0*/ tb_kyber_top__DOT__uut__DOT__u_src_idx12;
        SData/*11:0*/ tb_kyber_top__DOT__uut__DOT__ep_src_idx12;
        SData/*11:0*/ tb_kyber_top__DOT__uut__DOT__ep_src_next12;
        SData/*15:0*/ tb_kyber_top__DOT__uut__DOT__ep_term;
        SData/*15:0*/ tb_kyber_top__DOT__uut__DOT__epp_term_v;
        SData/*11:0*/ tb_kyber_top__DOT__uut__DOT__uidx;
        SData/*11:0*/ tb_kyber_top__DOT__uut__DOT__v_src_idx12;
        SData/*11:0*/ tb_kyber_top__DOT__uut__DOT__epp_src_idx12;
        SData/*11:0*/ tb_kyber_top__DOT__uut__DOT__vidx_w;
        SData/*8:0*/ tb_kyber_top__DOT__uut__DOT__vidx;
        SData/*8:0*/ tb_kyber_top__DOT__uut__DOT__bitpos;
        SData/*11:0*/ tb_kyber_top__DOT__uut__DOT__first_mis;
        SData/*11:0*/ tb_kyber_top__DOT__uut__DOT__sk_coeff_base;
        SData/*15:0*/ tb_kyber_top__DOT__uut__DOT__v_q;
        SData/*15:0*/ tb_kyber_top__DOT__uut__DOT__su_q;
        SData/*15:0*/ tb_kyber_top__DOT__uut__DOT__diff_q;
        SData/*10:0*/ tb_kyber_top__DOT__uut__DOT__u_hash__DOT__u_shake__DOT__sponge_inst__DOT__rate_bits;
        SData/*8:0*/ tb_kyber_top__DOT__uut__DOT__u_cbd__DOT__coeff_cnt;
        SData/*15:0*/ tb_kyber_top__DOT__uut__DOT__u_cbd__DOT__cbd_val;
        SData/*8:0*/ tb_kyber_top__DOT__uut__DOT__u_gm__DOT__coeff_cnt;
        SData/*11:0*/ tb_kyber_top__DOT__uut__DOT__u_gm__DOT__poly_base;
        SData/*10:0*/ tb_kyber_top__DOT__uut__DOT__u_gm__DOT__bit_cnt;
        SData/*15:0*/ tb_kyber_top__DOT__uut__DOT__u_ntt__DOT__dbg_call_ctr;
        SData/*15:0*/ tb_kyber_top__DOT__uut__DOT__u_ntt__DOT__dbg_call_id;
    };
    struct {
        SData/*15:0*/ tb_kyber_top__DOT__uut__DOT__u_ntt__DOT__ram0_dout_a;
        SData/*15:0*/ tb_kyber_top__DOT__uut__DOT__u_ntt__DOT__ram0_dout_b;
        SData/*15:0*/ tb_kyber_top__DOT__uut__DOT__u_ntt__DOT__ram1_dout_a;
        SData/*15:0*/ tb_kyber_top__DOT__uut__DOT__u_ntt__DOT__ram1_dout_b;
        SData/*15:0*/ tb_kyber_top__DOT__uut__DOT__u_ntt__DOT__zeta;
        SData/*15:0*/ tb_kyber_top__DOT__uut__DOT__u_ntt__DOT__bf_out_a;
        SData/*15:0*/ tb_kyber_top__DOT__uut__DOT__u_ntt__DOT__bf_out_b;
        SData/*15:0*/ tb_kyber_top__DOT__uut__DOT__u_ntt__DOT__u_butterfly__DOT__a;
        SData/*15:0*/ tb_kyber_top__DOT__uut__DOT__u_ntt__DOT__u_butterfly__DOT__b;
        SData/*15:0*/ tb_kyber_top__DOT__uut__DOT__u_ntt__DOT__u_butterfly__DOT__s1_a;
        SData/*15:0*/ tb_kyber_top__DOT__uut__DOT__u_ntt__DOT__u_butterfly__DOT__s1_sum_a_b;
        SData/*15:0*/ tb_kyber_top__DOT__uut__DOT__u_ntt__DOT__u_butterfly__DOT__s1_mont_res;
        SData/*15:0*/ tb_kyber_top__DOT__uut__DOT__u_ntt__DOT__u_butterfly__DOT__u_barrett_a__DOT__a;
        SData/*15:0*/ tb_kyber_top__DOT__uut__DOT__u_ntt__DOT__u_butterfly__DOT__u_barrett_b__DOT__a;
        SData/*15:0*/ tb_kyber_top__DOT__uut__DOT__u_pwma__DOT__bm_a0;
        SData/*15:0*/ tb_kyber_top__DOT__uut__DOT__u_pwma__DOT__bm_a1;
        SData/*15:0*/ tb_kyber_top__DOT__uut__DOT__u_pwma__DOT__bm_b0;
        SData/*15:0*/ tb_kyber_top__DOT__uut__DOT__u_pwma__DOT__bm_b1;
        SData/*15:0*/ tb_kyber_top__DOT__uut__DOT__u_pwma__DOT__bm_zeta;
        SData/*15:0*/ tb_kyber_top__DOT__uut__DOT__u_pwma__DOT__s1_zeta_base;
        SData/*15:0*/ tb_kyber_top__DOT__uut__DOT__u_pwma__DOT__s1_zeta_eff;
        SData/*15:0*/ tb_kyber_top__DOT__uut__DOT__u_pwma__DOT__s1_c0_old;
        SData/*15:0*/ tb_kyber_top__DOT__uut__DOT__u_pwma__DOT__s1_c1_old;
        SData/*15:0*/ tb_kyber_top__DOT__uut__DOT__u_pwma__DOT__s3_c0_old;
        SData/*15:0*/ tb_kyber_top__DOT__uut__DOT__u_pwma__DOT__s3_c1_old;
        SData/*15:0*/ tb_kyber_top__DOT__uut__DOT__u_pwma__DOT__base_c0;
        SData/*15:0*/ tb_kyber_top__DOT__uut__DOT__u_pwma__DOT__base_c1;
        SData/*15:0*/ tb_kyber_top__DOT__uut__DOT__u_pwma__DOT__u_basemul__DOT__s1_mont_00;
        SData/*15:0*/ tb_kyber_top__DOT__uut__DOT__u_pwma__DOT__u_basemul__DOT__s1_mont_11;
        SData/*15:0*/ tb_kyber_top__DOT__uut__DOT__u_pwma__DOT__u_basemul__DOT__s1_mont_sum;
        SData/*15:0*/ tb_kyber_top__DOT__uut__DOT__u_pwma__DOT__u_basemul__DOT__s1_zeta;
        SData/*15:0*/ tb_kyber_top__DOT__uut__DOT__u_pwma__DOT__u_basemul__DOT__s2_mont_00;
        SData/*15:0*/ tb_kyber_top__DOT__uut__DOT__u_pwma__DOT__u_basemul__DOT__s2_mont_11;
        SData/*15:0*/ tb_kyber_top__DOT__uut__DOT__u_pwma__DOT__u_basemul__DOT__s2_mont_sum;
        SData/*15:0*/ tb_kyber_top__DOT__uut__DOT__u_pwma__DOT__u_basemul__DOT__s2_mont_zeta;
        SData/*15:0*/ tb_kyber_top__DOT__uut__DOT__u_pwma__DOT__u_basemul__DOT__u_barrett_c0__DOT__a;
        SData/*15:0*/ tb_kyber_top__DOT__uut__DOT__u_pwma__DOT__u_basemul__DOT__u_barrett_c1__DOT__a;
        SData/*15:0*/ tb_kyber_top__DOT__uut__DOT__u_pwma__DOT__u_barrett_acc_c0__DOT__a;
        SData/*15:0*/ tb_kyber_top__DOT__uut__DOT__u_pwma__DOT__u_barrett_acc_c1__DOT__a;
        SData/*10:0*/ tb_kyber_top__DOT__uut__DOT__u_cmp__DOT__cnt;
        SData/*11:0*/ tb_kyber_top__DOT__uut__DOT__u_a_cache__DOT__addr_a;
        SData/*8:0*/ tb_kyber_top__DOT__uut__DOT__u_ct_pack__DOT__group_idx;
        SData/*8:0*/ tb_kyber_top__DOT__uut__DOT__u_ct_pack__DOT__v_addr_w;
        SData/*15:0*/ tb_kyber_top__DOT__uut__DOT__u_ct_pack__DOT__c0;
        SData/*15:0*/ tb_kyber_top__DOT__uut__DOT__u_ct_pack__DOT__c1;
        SData/*15:0*/ tb_kyber_top__DOT__uut__DOT__u_ct_pack__DOT__c2;
        SData/*15:0*/ tb_kyber_top__DOT__uut__DOT__u_ct_pack__DOT__c3;
        SData/*15:0*/ tb_kyber_top__DOT__uut__DOT__u_ct_pack__DOT__c4;
        SData/*15:0*/ tb_kyber_top__DOT__uut__DOT__u_ct_pack__DOT__c5;
        SData/*15:0*/ tb_kyber_top__DOT__uut__DOT__u_ct_pack__DOT__c6;
        SData/*15:0*/ tb_kyber_top__DOT__uut__DOT__u_ct_pack__DOT__c7;
        SData/*15:0*/ tb_kyber_top__DOT__uut__DOT__u_ct_pack__DOT__u_codec__DOT____VlemCall_11__decompress_d;
        SData/*15:0*/ tb_kyber_top__DOT__uut__DOT__u_ct_pack__DOT__u_codec__DOT____VlemCall_10__decompress_d;
        SData/*15:0*/ tb_kyber_top__DOT__uut__DOT__u_ct_pack__DOT__u_codec__DOT____VlemCall_9__decompress_d;
        SData/*15:0*/ tb_kyber_top__DOT__uut__DOT__u_ct_pack__DOT__u_codec__DOT____VlemCall_8__decompress_d;
        SData/*15:0*/ tb_kyber_top__DOT__uut__DOT__u_ct_pack__DOT__u_codec__DOT____VlemCall_7__decompress_d;
        SData/*15:0*/ tb_kyber_top__DOT__uut__DOT__u_ct_pack__DOT__u_codec__DOT____VlemCall_6__decompress_d;
        SData/*15:0*/ tb_kyber_top__DOT__uut__DOT__u_ct_pack__DOT__u_codec__DOT____VlemCall_5__decompress_d;
        SData/*15:0*/ tb_kyber_top__DOT__uut__DOT__u_ct_pack__DOT__u_codec__DOT____VlemCall_4__decompress_d;
        SData/*15:0*/ tb_kyber_top__DOT__uut__DOT__u_ct_pack__DOT__u_codec__DOT____VlemCall_3__decompress_d;
        SData/*15:0*/ tb_kyber_top__DOT__uut__DOT__u_ct_pack__DOT__u_codec__DOT____VlemCall_2__decompress_d;
        SData/*15:0*/ tb_kyber_top__DOT__uut__DOT__u_ct_pack__DOT__u_codec__DOT____VlemCall_1__decompress_d;
        SData/*15:0*/ tb_kyber_top__DOT__uut__DOT__u_ct_pack__DOT__u_codec__DOT____VlemCall_0__decompress_d;
        SData/*10:0*/ tb_kyber_top__DOT__uut__DOT__u_ct_pack__DOT__u_codec__DOT__t0;
    };
    struct {
        SData/*10:0*/ tb_kyber_top__DOT__uut__DOT__u_ct_pack__DOT__u_codec__DOT__t1;
        SData/*10:0*/ tb_kyber_top__DOT__uut__DOT__u_ct_pack__DOT__u_codec__DOT__t2;
        SData/*10:0*/ tb_kyber_top__DOT__uut__DOT__u_ct_pack__DOT__u_codec__DOT__t3;
        SData/*10:0*/ tb_kyber_top__DOT__uut__DOT__u_ct_pack__DOT__u_codec__DOT__t4;
        SData/*10:0*/ tb_kyber_top__DOT__uut__DOT__u_ct_pack__DOT__u_codec__DOT__t5;
        SData/*10:0*/ tb_kyber_top__DOT__uut__DOT__u_ct_pack__DOT__u_codec__DOT__t6;
        SData/*10:0*/ tb_kyber_top__DOT__uut__DOT__u_ct_pack__DOT__u_codec__DOT__t7;
        SData/*15:0*/ tb_kyber_top__DOT__uut__DOT__u_dec_codec__DOT____VlemCall_11__decompress_d;
        SData/*15:0*/ tb_kyber_top__DOT__uut__DOT__u_dec_codec__DOT____VlemCall_10__decompress_d;
        SData/*15:0*/ tb_kyber_top__DOT__uut__DOT__u_dec_codec__DOT____VlemCall_9__decompress_d;
        SData/*15:0*/ tb_kyber_top__DOT__uut__DOT__u_dec_codec__DOT____VlemCall_8__decompress_d;
        SData/*15:0*/ tb_kyber_top__DOT__uut__DOT__u_dec_codec__DOT____VlemCall_7__decompress_d;
        SData/*15:0*/ tb_kyber_top__DOT__uut__DOT__u_dec_codec__DOT____VlemCall_6__decompress_d;
        SData/*15:0*/ tb_kyber_top__DOT__uut__DOT__u_dec_codec__DOT____VlemCall_5__decompress_d;
        SData/*15:0*/ tb_kyber_top__DOT__uut__DOT__u_dec_codec__DOT____VlemCall_4__decompress_d;
        SData/*15:0*/ tb_kyber_top__DOT__uut__DOT__u_dec_codec__DOT____VlemCall_3__decompress_d;
        SData/*15:0*/ tb_kyber_top__DOT__uut__DOT__u_dec_codec__DOT____VlemCall_2__decompress_d;
        SData/*15:0*/ tb_kyber_top__DOT__uut__DOT__u_dec_codec__DOT____VlemCall_1__decompress_d;
        SData/*15:0*/ tb_kyber_top__DOT__uut__DOT__u_dec_codec__DOT____VlemCall_0__decompress_d;
        SData/*10:0*/ tb_kyber_top__DOT__uut__DOT__u_dec_codec__DOT__t0;
        SData/*10:0*/ tb_kyber_top__DOT__uut__DOT__u_dec_codec__DOT__t1;
        SData/*10:0*/ tb_kyber_top__DOT__uut__DOT__u_dec_codec__DOT__t2;
        SData/*10:0*/ tb_kyber_top__DOT__uut__DOT__u_dec_codec__DOT__t3;
        SData/*10:0*/ tb_kyber_top__DOT__uut__DOT__u_dec_codec__DOT__t4;
        SData/*10:0*/ tb_kyber_top__DOT__uut__DOT__u_dec_codec__DOT__t5;
        SData/*10:0*/ tb_kyber_top__DOT__uut__DOT__u_dec_codec__DOT__t6;
        SData/*10:0*/ tb_kyber_top__DOT__uut__DOT__u_dec_codec__DOT__t7;
        SData/*10:0*/ __Vfunc_tb_kyber_top__DOT__uut__DOT__u_ct_pack__DOT__u_codec__DOT__decompress_d__65__x;
        SData/*10:0*/ __Vfunc_tb_kyber_top__DOT__uut__DOT__u_ct_pack__DOT__u_codec__DOT__decompress_d__66__x;
        SData/*10:0*/ __Vfunc_tb_kyber_top__DOT__uut__DOT__u_ct_pack__DOT__u_codec__DOT__decompress_d__67__x;
        SData/*10:0*/ __Vfunc_tb_kyber_top__DOT__uut__DOT__u_ct_pack__DOT__u_codec__DOT__decompress_d__68__x;
        SData/*10:0*/ __Vfunc_tb_kyber_top__DOT__uut__DOT__u_ct_pack__DOT__u_codec__DOT__decompress_d__69__x;
        SData/*10:0*/ __Vfunc_tb_kyber_top__DOT__uut__DOT__u_ct_pack__DOT__u_codec__DOT__decompress_d__70__x;
        SData/*10:0*/ __Vfunc_tb_kyber_top__DOT__uut__DOT__u_ct_pack__DOT__u_codec__DOT__decompress_d__71__x;
        SData/*10:0*/ __Vfunc_tb_kyber_top__DOT__uut__DOT__u_ct_pack__DOT__u_codec__DOT__decompress_d__72__x;
        SData/*10:0*/ __Vfunc_tb_kyber_top__DOT__uut__DOT__u_ct_pack__DOT__u_codec__DOT__compress_d__73__Vfuncout;
        SData/*15:0*/ __Vfunc_tb_kyber_top__DOT__uut__DOT__u_ct_pack__DOT__u_codec__DOT__compress_d__73__c;
        SData/*10:0*/ __Vfunc_tb_kyber_top__DOT__uut__DOT__u_ct_pack__DOT__u_codec__DOT__compress_d__74__Vfuncout;
        SData/*15:0*/ __Vfunc_tb_kyber_top__DOT__uut__DOT__u_ct_pack__DOT__u_codec__DOT__compress_d__74__c;
        SData/*10:0*/ __Vfunc_tb_kyber_top__DOT__uut__DOT__u_ct_pack__DOT__u_codec__DOT__compress_d__75__Vfuncout;
        SData/*15:0*/ __Vfunc_tb_kyber_top__DOT__uut__DOT__u_ct_pack__DOT__u_codec__DOT__compress_d__75__c;
        SData/*10:0*/ __Vfunc_tb_kyber_top__DOT__uut__DOT__u_ct_pack__DOT__u_codec__DOT__compress_d__76__Vfuncout;
        SData/*15:0*/ __Vfunc_tb_kyber_top__DOT__uut__DOT__u_ct_pack__DOT__u_codec__DOT__compress_d__76__c;
        SData/*10:0*/ __Vfunc_tb_kyber_top__DOT__uut__DOT__u_ct_pack__DOT__u_codec__DOT__compress_d__77__Vfuncout;
        SData/*15:0*/ __Vfunc_tb_kyber_top__DOT__uut__DOT__u_ct_pack__DOT__u_codec__DOT__compress_d__77__c;
        SData/*10:0*/ __Vfunc_tb_kyber_top__DOT__uut__DOT__u_ct_pack__DOT__u_codec__DOT__compress_d__78__Vfuncout;
        SData/*15:0*/ __Vfunc_tb_kyber_top__DOT__uut__DOT__u_ct_pack__DOT__u_codec__DOT__compress_d__78__c;
        SData/*10:0*/ __Vfunc_tb_kyber_top__DOT__uut__DOT__u_ct_pack__DOT__u_codec__DOT__compress_d__79__Vfuncout;
        SData/*15:0*/ __Vfunc_tb_kyber_top__DOT__uut__DOT__u_ct_pack__DOT__u_codec__DOT__compress_d__79__c;
        SData/*10:0*/ __Vfunc_tb_kyber_top__DOT__uut__DOT__u_ct_pack__DOT__u_codec__DOT__compress_d__80__Vfuncout;
        SData/*15:0*/ __Vfunc_tb_kyber_top__DOT__uut__DOT__u_ct_pack__DOT__u_codec__DOT__compress_d__80__c;
        SData/*10:0*/ __Vfunc_tb_kyber_top__DOT__uut__DOT__u_ct_pack__DOT__u_codec__DOT__decompress_d__81__x;
        SData/*10:0*/ __Vfunc_tb_kyber_top__DOT__uut__DOT__u_ct_pack__DOT__u_codec__DOT__decompress_d__82__x;
        SData/*10:0*/ __Vfunc_tb_kyber_top__DOT__uut__DOT__u_ct_pack__DOT__u_codec__DOT__decompress_d__83__x;
        SData/*10:0*/ __Vfunc_tb_kyber_top__DOT__uut__DOT__u_ct_pack__DOT__u_codec__DOT__decompress_d__84__x;
        SData/*10:0*/ __Vfunc_tb_kyber_top__DOT__uut__DOT__u_ct_pack__DOT__u_codec__DOT__compress_d__85__Vfuncout;
        SData/*15:0*/ __Vfunc_tb_kyber_top__DOT__uut__DOT__u_ct_pack__DOT__u_codec__DOT__compress_d__85__c;
        SData/*10:0*/ __Vfunc_tb_kyber_top__DOT__uut__DOT__u_ct_pack__DOT__u_codec__DOT__compress_d__86__Vfuncout;
        SData/*15:0*/ __Vfunc_tb_kyber_top__DOT__uut__DOT__u_ct_pack__DOT__u_codec__DOT__compress_d__86__c;
        SData/*10:0*/ __Vfunc_tb_kyber_top__DOT__uut__DOT__u_ct_pack__DOT__u_codec__DOT__compress_d__87__Vfuncout;
        SData/*15:0*/ __Vfunc_tb_kyber_top__DOT__uut__DOT__u_ct_pack__DOT__u_codec__DOT__compress_d__87__c;
        SData/*10:0*/ __Vfunc_tb_kyber_top__DOT__uut__DOT__u_ct_pack__DOT__u_codec__DOT__compress_d__88__Vfuncout;
        SData/*15:0*/ __Vfunc_tb_kyber_top__DOT__uut__DOT__u_ct_pack__DOT__u_codec__DOT__compress_d__88__c;
        SData/*10:0*/ __Vfunc_tb_kyber_top__DOT__uut__DOT__u_dec_codec__DOT__decompress_d__89__x;
    };
    struct {
        SData/*10:0*/ __Vfunc_tb_kyber_top__DOT__uut__DOT__u_dec_codec__DOT__decompress_d__90__x;
        SData/*10:0*/ __Vfunc_tb_kyber_top__DOT__uut__DOT__u_dec_codec__DOT__decompress_d__91__x;
        SData/*10:0*/ __Vfunc_tb_kyber_top__DOT__uut__DOT__u_dec_codec__DOT__decompress_d__92__x;
        SData/*10:0*/ __Vfunc_tb_kyber_top__DOT__uut__DOT__u_dec_codec__DOT__decompress_d__93__x;
        SData/*10:0*/ __Vfunc_tb_kyber_top__DOT__uut__DOT__u_dec_codec__DOT__decompress_d__94__x;
        SData/*10:0*/ __Vfunc_tb_kyber_top__DOT__uut__DOT__u_dec_codec__DOT__decompress_d__95__x;
        SData/*10:0*/ __Vfunc_tb_kyber_top__DOT__uut__DOT__u_dec_codec__DOT__decompress_d__96__x;
        SData/*10:0*/ __Vfunc_tb_kyber_top__DOT__uut__DOT__u_dec_codec__DOT__decompress_d__105__x;
        SData/*10:0*/ __Vfunc_tb_kyber_top__DOT__uut__DOT__u_dec_codec__DOT__decompress_d__106__x;
        SData/*10:0*/ __Vfunc_tb_kyber_top__DOT__uut__DOT__u_dec_codec__DOT__decompress_d__107__x;
        SData/*10:0*/ __Vfunc_tb_kyber_top__DOT__uut__DOT__u_dec_codec__DOT__decompress_d__108__x;
        IData/*31:0*/ tb_kyber_top__DOT__ext_addr;
        IData/*31:0*/ tb_kyber_top__DOT__ext_dout;
        IData/*31:0*/ tb_kyber_top__DOT__mode_sel;
        IData/*31:0*/ tb_kyber_top__DOT__check_ref;
        IData/*31:0*/ tb_kyber_top__DOT__compare_errors;
        IData/*31:0*/ tb_kyber_top__DOT__dump_ref;
        IData/*31:0*/ tb_kyber_top__DOT__clear_tb_ram__Vstatic__i;
        IData/*31:0*/ tb_kyber_top__DOT__print_hex_block__Vstatic__i;
        IData/*31:0*/ tb_kyber_top__DOT__dump_hex_file__Vstatic__i;
        IData/*31:0*/ tb_kyber_top__DOT__dump_hex_file__Vstatic__fd;
        IData/*31:0*/ tb_kyber_top__DOT__dump_mem_file__Vstatic__i;
        IData/*31:0*/ tb_kyber_top__DOT__dump_mem_file__Vstatic__fd;
        IData/*31:0*/ tb_kyber_top__DOT__dump_ref_vectors__Vstatic__mode_tag;
        IData/*31:0*/ tb_kyber_top__DOT__run_mode_report__Vstatic__pk_bytes;
        IData/*31:0*/ tb_kyber_top__DOT__run_mode_report__Vstatic__sk_bytes;
        IData/*31:0*/ tb_kyber_top__DOT__run_mode_report__Vstatic__ct_bytes;
        IData/*31:0*/ tb_kyber_top__DOT__run_mode_report__Vstatic__mode_tag;
        IData/*31:0*/ tb_kyber_top__DOT__run_mode_report__Vstatic__host_cpu_sk_assemble__DOT__bi;
        IData/*31:0*/ tb_kyber_top__DOT__run_mode_report__Vstatic__host_cpu_sk_assemble__DOT__s_sz;
        IData/*31:0*/ tb_kyber_top__DOT__compare_with_file__Vstatic__i;
        IData/*31:0*/ tb_kyber_top__DOT__compare_with_file__Vstatic__fd;
        IData/*31:0*/ tb_kyber_top__DOT__compare_with_file__Vstatic__mism;
        VlWide<8>/*255:0*/ tb_kyber_top__DOT__uut__DOT____VlemCall_14__flip_bytes_32;
        VlWide<8>/*255:0*/ tb_kyber_top__DOT__uut__DOT____VlemCall_13__flip_bytes_32;
        VlWide<8>/*255:0*/ tb_kyber_top__DOT__uut__DOT____VlemCall_12__flip_bytes_32;
        VlWide<8>/*255:0*/ tb_kyber_top__DOT__uut__DOT____VlemCall_11__flip_bytes_32;
        VlWide<8>/*255:0*/ tb_kyber_top__DOT__uut__DOT____VlemCall_10__flip_bytes_32;
        VlWide<8>/*255:0*/ tb_kyber_top__DOT__uut__DOT____VlemCall_9__flip_bytes_32;
        VlWide<8>/*255:0*/ tb_kyber_top__DOT__uut__DOT____VlemCall_7__flip_bytes_32;
        VlWide<8>/*255:0*/ tb_kyber_top__DOT__uut__DOT____VlemCall_6__flip_bytes_32;
        VlWide<8>/*255:0*/ tb_kyber_top__DOT__uut__DOT____VlemCall_5__flip_bytes_32;
        VlWide<8>/*255:0*/ tb_kyber_top__DOT__uut__DOT____VlemCall_4__flip_bytes_32;
        VlWide<8>/*255:0*/ tb_kyber_top__DOT__uut__DOT____VlemCall_3__flip_bytes_32;
        VlWide<8>/*255:0*/ tb_kyber_top__DOT__uut__DOT____VlemCall_2__flip_bytes_32;
        VlWide<8>/*255:0*/ tb_kyber_top__DOT__uut__DOT____VlemCall_1__flip_bytes_32;
        IData/*31:0*/ tb_kyber_top__DOT__uut__DOT__ext_din;
        VlWide<8>/*255:0*/ tb_kyber_top__DOT__uut__DOT__reg_rho;
        VlWide<8>/*255:0*/ tb_kyber_top__DOT__uut__DOT__reg_sigma;
        VlWide<8>/*255:0*/ tb_kyber_top__DOT__uut__DOT__reg_z;
        VlWide<8>/*255:0*/ tb_kyber_top__DOT__uut__DOT__reg_m;
        VlWide<8>/*255:0*/ tb_kyber_top__DOT__uut__DOT__reg_K_bar;
        VlWide<8>/*255:0*/ tb_kyber_top__DOT__uut__DOT__reg_r_seed;
        VlWide<8>/*255:0*/ tb_kyber_top__DOT__uut__DOT__reg_H_pk;
        VlWide<8>/*255:0*/ tb_kyber_top__DOT__uut__DOT__reg_H_c;
        VlWide<16>/*511:0*/ tb_kyber_top__DOT__uut__DOT__reg_trng_seed;
        IData/*31:0*/ tb_kyber_top__DOT__uut__DOT__biu;
        IData/*31:0*/ tb_kyber_top__DOT__uut__DOT__flip_bytes_32__Vstatic__i;
        IData/*31:0*/ tb_kyber_top__DOT__uut__DOT__barrett_reduce_q__Vstatic__t;
        IData/*31:0*/ tb_kyber_top__DOT__uut__DOT__barrett_reduce_q__Vstatic__r;
        VlWide<34>/*1087:0*/ tb_kyber_top__DOT__uut__DOT__hash_din;
        VlWide<34>/*1087:0*/ tb_kyber_top__DOT__uut__DOT__hash_stream_din;
        VlWide<48>/*1535:0*/ tb_kyber_top__DOT__uut__DOT__hash_dout;
        IData/*31:0*/ tb_kyber_top__DOT__uut__DOT__cmp_data_c;
    };
    struct {
        IData/*31:0*/ tb_kyber_top__DOT__uut__DOT__cmp_data_c_prime;
        VlWide<4>/*127:0*/ tb_kyber_top__DOT__uut__DOT__dec_unpack_coeff_latch;
        VlWide<3>/*87:0*/ tb_kyber_top__DOT__uut__DOT__dec_codec_bytes_w;
        VlWide<4>/*127:0*/ tb_kyber_top__DOT__uut__DOT__dec_codec_coeff_out;
        IData/*31:0*/ tb_kyber_top__DOT__uut__DOT__ct_pack_ext_addr;
        IData/*31:0*/ tb_kyber_top__DOT__uut__DOT__ct_pack_ext_dout;
        IData/*31:0*/ tb_kyber_top__DOT__uut__DOT__pack_pk_addr;
        IData/*31:0*/ tb_kyber_top__DOT__uut__DOT__pack_sk_addr;
        IData/*31:0*/ tb_kyber_top__DOT__uut__DOT__pack_pk_byte_idx;
        IData/*31:0*/ tb_kyber_top__DOT__uut__DOT__bi;
        IData/*31:0*/ tb_kyber_top__DOT__uut__DOT__bi2;
        IData/*31:0*/ tb_kyber_top__DOT__uut__DOT__ci;
        IData/*16:0*/ tb_kyber_top__DOT__uut__DOT__su;
        IData/*16:0*/ tb_kyber_top__DOT__uut__DOT__sv;
        IData/*16:0*/ tb_kyber_top__DOT__uut__DOT__v_c;
        IData/*16:0*/ tb_kyber_top__DOT__uut__DOT__su_c;
        IData/*16:0*/ tb_kyber_top__DOT__uut__DOT__diff_q17;
        IData/*31:0*/ tb_kyber_top__DOT__uut__DOT__tmsg32;
        IData/*31:0*/ tb_kyber_top__DOT__uut__DOT__sk_pair_base;
        VlWide<34>/*1087:0*/ tb_kyber_top__DOT__uut__DOT__u_hash__DOT__u_shake__DOT__eff_din;
        VlWide<50>/*1599:0*/ tb_kyber_top__DOT__uut__DOT__u_hash__DOT__u_shake__DOT__sponge_inst__DOT__sponge_state;
        VlWide<34>/*1087:0*/ tb_kyber_top__DOT__uut__DOT__u_hash__DOT__u_shake__DOT__sponge_inst__DOT__beat_din;
        VlWide<50>/*1599:0*/ tb_kyber_top__DOT__uut__DOT__u_hash__DOT__u_shake__DOT__sponge_inst__DOT__f_out;
        IData/*31:0*/ tb_kyber_top__DOT__uut__DOT__u_hash__DOT__u_shake__DOT__sponge_inst__DOT__i;
        VlWide<50>/*1599:0*/ tb_kyber_top__DOT__uut__DOT__u_hash__DOT__u_shake__DOT__sponge_inst__DOT__absorb_next;
        VlWide<50>/*1599:0*/ tb_kyber_top__DOT__uut__DOT__u_hash__DOT__u_shake__DOT__sponge_inst__DOT__f_inst__DOT__curr_state;
        VlWide<50>/*1599:0*/ tb_kyber_top__DOT__uut__DOT__u_hash__DOT__u_shake__DOT__sponge_inst__DOT__f_inst__DOT__next_state;
        VlWide<48>/*1535:0*/ tb_kyber_top__DOT__uut__DOT__u_cbd__DOT__shift_reg;
        VlWide<8>/*255:0*/ tb_kyber_top__DOT__uut__DOT__u_gm__DOT____VlemCall_1__flip_bytes_32;
        VlWide<8>/*255:0*/ tb_kyber_top__DOT__uut__DOT__u_gm__DOT____VlemCall_0__flip_bytes_32;
        IData/*31:0*/ tb_kyber_top__DOT__uut__DOT__u_gm__DOT__flip_bytes_32__Vstatic__fi;
        VlWide<9>/*271:0*/ tb_kyber_top__DOT__uut__DOT__u_gm__DOT__xof_din;
        VlWide<42>/*1343:0*/ tb_kyber_top__DOT__uut__DOT__u_gm__DOT__xof_squeeze_data;
        VlWide<42>/*1343:0*/ tb_kyber_top__DOT__uut__DOT__u_gm__DOT__bit_buf;
        VlWide<50>/*1599:0*/ tb_kyber_top__DOT__uut__DOT__u_gm__DOT__u_xof__DOT__sponge_state;
        VlWide<50>/*1599:0*/ tb_kyber_top__DOT__uut__DOT__u_gm__DOT__u_xof__DOT__f_out;
        VlWide<50>/*1599:0*/ tb_kyber_top__DOT__uut__DOT__u_gm__DOT__u_xof__DOT__keccak_inst__DOT__curr_state;
        VlWide<50>/*1599:0*/ tb_kyber_top__DOT__uut__DOT__u_gm__DOT__u_xof__DOT__keccak_inst__DOT__next_state;
        IData/*31:0*/ tb_kyber_top__DOT__uut__DOT__u_ntt__DOT__u_butterfly__DOT__prod;
        IData/*31:0*/ tb_kyber_top__DOT__uut__DOT__u_pwma__DOT__u_basemul__DOT__mul_a0_b0;
        IData/*31:0*/ tb_kyber_top__DOT__uut__DOT__u_pwma__DOT__u_basemul__DOT__mul_a1_b1;
        IData/*31:0*/ tb_kyber_top__DOT__uut__DOT__u_pwma__DOT__u_basemul__DOT__mul_sum;
        IData/*31:0*/ tb_kyber_top__DOT__uut__DOT__u_pwma__DOT__u_basemul__DOT__mul_zeta;
        IData/*31:0*/ tb_kyber_top__DOT__uut__DOT__u_ct_pack__DOT__byte_idx;
        VlWide<4>/*127:0*/ tb_kyber_top__DOT__uut__DOT__u_ct_pack__DOT__codec_coeff_in;
        VlWide<3>/*87:0*/ tb_kyber_top__DOT__uut__DOT__u_ct_pack__DOT__codec_bytes_in;
        VlWide<4>/*127:0*/ tb_kyber_top__DOT__uut__DOT__u_ct_pack__DOT__codec_coeff_out;
        VlWide<3>/*87:0*/ tb_kyber_top__DOT__uut__DOT__u_ct_pack__DOT__codec_bytes_out;
        IData/*31:0*/ tb_kyber_top__DOT__uut__DOT__u_ct_pack__DOT__u_codec__DOT__compress_d__Vstatic__u;
        IData/*31:0*/ tb_kyber_top__DOT__uut__DOT__u_ct_pack__DOT__u_codec__DOT__compress_d__Vstatic__t;
        IData/*31:0*/ tb_kyber_top__DOT__uut__DOT__u_ct_pack__DOT__u_codec__DOT__compress_d__Vstatic__m;
        IData/*31:0*/ tb_kyber_top__DOT__uut__DOT__u_ct_pack__DOT__u_codec__DOT__decompress_d__Vstatic__t;
        VlWide<3>/*87:0*/ tb_kyber_top__DOT__uut__DOT__u_dec_codec__DOT__bytes_out;
        IData/*31:0*/ tb_kyber_top__DOT__uut__DOT__u_dec_codec__DOT__compress_d__Vstatic__u;
        IData/*31:0*/ tb_kyber_top__DOT__uut__DOT__u_dec_codec__DOT__compress_d__Vstatic__t;
        IData/*31:0*/ tb_kyber_top__DOT__uut__DOT__u_dec_codec__DOT__compress_d__Vstatic__m;
        IData/*31:0*/ tb_kyber_top__DOT__uut__DOT__u_dec_codec__DOT__decompress_d__Vstatic__t;
        VlWide<50>/*1599:0*/ __Vdly__tb_kyber_top__DOT__uut__DOT__u_hash__DOT__u_shake__DOT__sponge_inst__DOT__sponge_state;
        VlWide<50>/*1599:0*/ __Vdly__tb_kyber_top__DOT__uut__DOT__u_hash__DOT__u_shake__DOT__sponge_inst__DOT__f_inst__DOT__curr_state;
        IData/*31:0*/ __VactIterCount;
        IData/*31:0*/ __VinactIterCount;
        IData/*31:0*/ __Vi;
        QData/*63:0*/ tb_kyber_top__DOT__uut__DOT__u_hash__DOT__u_shake__DOT__sponge_inst__DOT__f_inst__DOT__rc;
        QData/*63:0*/ tb_kyber_top__DOT__uut__DOT__u_gm__DOT__u_xof__DOT__keccak_inst__DOT__rc;
    };
    struct {
        VlUnpacked<IData/*31:0*/, 8192> tb_kyber_top__DOT__tb_ram;
        VlUnpacked<CData/*7:0*/, 8192> tb_kyber_top__DOT__exp_buf;
        VlUnpacked<CData/*7:0*/, 2048> tb_kyber_top__DOT__uut__DOT__u_hpk_ram__DOT__ram;
        VlUnpacked<CData/*7:0*/, 2048> tb_kyber_top__DOT__uut__DOT__u_ct_ram__DOT__ram;
        VlUnpacked<CData/*7:0*/, 2048> tb_kyber_top__DOT__uut__DOT__u_ct_dec_ram__DOT__ram;
        VlUnpacked<CData/*7:0*/, 2048> tb_kyber_top__DOT__uut__DOT__u_ct_reenc_ram__DOT__ram;
        VlUnpacked<VlUnpacked<QData/*63:0*/, 5>, 5> tb_kyber_top__DOT__uut__DOT__u_hash__DOT__u_shake__DOT__sponge_inst__DOT__f_inst__DOT__round_inst__DOT__state;
        VlUnpacked<QData/*63:0*/, 5> tb_kyber_top__DOT__uut__DOT__u_hash__DOT__u_shake__DOT__sponge_inst__DOT__f_inst__DOT__round_inst__DOT__c;
        VlUnpacked<QData/*63:0*/, 5> tb_kyber_top__DOT__uut__DOT__u_hash__DOT__u_shake__DOT__sponge_inst__DOT__f_inst__DOT__round_inst__DOT__d;
        VlUnpacked<VlUnpacked<QData/*63:0*/, 5>, 5> tb_kyber_top__DOT__uut__DOT__u_hash__DOT__u_shake__DOT__sponge_inst__DOT__f_inst__DOT__round_inst__DOT__theta_state;
        VlUnpacked<VlUnpacked<QData/*63:0*/, 5>, 5> tb_kyber_top__DOT__uut__DOT__u_hash__DOT__u_shake__DOT__sponge_inst__DOT__f_inst__DOT__round_inst__DOT__rho_pi_state;
        VlUnpacked<VlUnpacked<QData/*63:0*/, 5>, 5> tb_kyber_top__DOT__uut__DOT__u_hash__DOT__u_shake__DOT__sponge_inst__DOT__f_inst__DOT__round_inst__DOT__chi_state;
        VlUnpacked<VlUnpacked<QData/*63:0*/, 5>, 5> tb_kyber_top__DOT__uut__DOT__u_hash__DOT__u_shake__DOT__sponge_inst__DOT__f_inst__DOT__round_inst__DOT__iota_state;
        VlUnpacked<VlUnpacked<QData/*63:0*/, 5>, 5> tb_kyber_top__DOT__uut__DOT__u_gm__DOT__u_xof__DOT__keccak_inst__DOT__round_inst__DOT__state;
        VlUnpacked<QData/*63:0*/, 5> tb_kyber_top__DOT__uut__DOT__u_gm__DOT__u_xof__DOT__keccak_inst__DOT__round_inst__DOT__c;
        VlUnpacked<QData/*63:0*/, 5> tb_kyber_top__DOT__uut__DOT__u_gm__DOT__u_xof__DOT__keccak_inst__DOT__round_inst__DOT__d;
        VlUnpacked<VlUnpacked<QData/*63:0*/, 5>, 5> tb_kyber_top__DOT__uut__DOT__u_gm__DOT__u_xof__DOT__keccak_inst__DOT__round_inst__DOT__theta_state;
        VlUnpacked<VlUnpacked<QData/*63:0*/, 5>, 5> tb_kyber_top__DOT__uut__DOT__u_gm__DOT__u_xof__DOT__keccak_inst__DOT__round_inst__DOT__rho_pi_state;
        VlUnpacked<VlUnpacked<QData/*63:0*/, 5>, 5> tb_kyber_top__DOT__uut__DOT__u_gm__DOT__u_xof__DOT__keccak_inst__DOT__round_inst__DOT__chi_state;
        VlUnpacked<VlUnpacked<QData/*63:0*/, 5>, 5> tb_kyber_top__DOT__uut__DOT__u_gm__DOT__u_xof__DOT__keccak_inst__DOT__round_inst__DOT__iota_state;
        VlUnpacked<CData/*7:0*/, 3> tb_kyber_top__DOT__uut__DOT__u_ntt__DOT__delay_addr_a;
        VlUnpacked<CData/*7:0*/, 3> tb_kyber_top__DOT__uut__DOT__u_ntt__DOT__delay_addr_b;
        VlUnpacked<CData/*0:0*/, 3> tb_kyber_top__DOT__uut__DOT__u_ntt__DOT__delay_we;
        VlUnpacked<SData/*15:0*/, 128> tb_kyber_top__DOT__uut__DOT__u_ntt__DOT__u_twiddle__DOT__rom;
        VlUnpacked<SData/*15:0*/, 256> tb_kyber_top__DOT__uut__DOT__u_ntt__DOT__u_ram0__DOT__ram;
        VlUnpacked<SData/*15:0*/, 256> tb_kyber_top__DOT__uut__DOT__u_ntt__DOT__u_ram1__DOT__ram;
        VlUnpacked<SData/*15:0*/, 128> tb_kyber_top__DOT__uut__DOT__u_twiddle_pwma__DOT__rom;
        VlUnpacked<SData/*15:0*/, 4096> tb_kyber_top__DOT__uut__DOT__u_a_cache__DOT__bram;
        VlUnpacked<SData/*15:0*/, 4096> tb_kyber_top__DOT__uut__DOT__u_ram__DOT__bram;
        VlUnpacked<SData/*15:0*/, 4096> tb_kyber_top__DOT__uut__DOT__u_enc_scratch__DOT__bram;
        VlUnpacked<QData/*63:0*/, 1> __VstlTriggered;
        VlUnpacked<QData/*63:0*/, 1> __VactTriggered;
        VlUnpacked<QData/*63:0*/, 1> __VactTriggeredAcc;
        VlUnpacked<QData/*63:0*/, 1> __VnbaTriggered;
        VlUnpacked<CData/*0:0*/, 5> __Vm_traceActivity;
    };
    std::string __Vtask_tb_kyber_top__DOT__compare_with_file__11__fname;
    std::string __Vtask_tb_kyber_top__DOT__compare_with_file__12__fname;
    std::string __Vtask_tb_kyber_top__DOT__dump_hex_file__17__fname;
    std::string __Vtask_tb_kyber_top__DOT__compare_with_file__18__fname;
    std::string __Vtask_tb_kyber_top__DOT__compare_with_file__19__fname;
    std::string __Vtask_tb_kyber_top__DOT__compare_with_file__22__fname;
    std::string __Vtask_tb_kyber_top__DOT__dump_mem_file__24__fname;
    std::string __Vtask_tb_kyber_top__DOT__dump_mem_file__25__fname;
    std::string __Vtask_tb_kyber_top__DOT__dump_mem_file__26__fname;
    std::string __Vtask_tb_kyber_top__DOT__dump_mem_file__27__fname;
    std::string __Vtask_tb_kyber_top__DOT__dump_mem_file__28__fname;
    std::string __Vtask_tb_kyber_top__DOT__dump_mem_file__30__fname;
    std::string __Vtask_tb_kyber_top__DOT__dump_mem_file__31__fname;
    std::string __Vtask_tb_kyber_top__DOT__dump_mem_file__32__fname;
    std::string __Vtask_tb_kyber_top__DOT__dump_mem_file__33__fname;
    std::string __Vtask_tb_kyber_top__DOT__dump_mem_file__34__fname;
    VlDelayScheduler __VdlySched;
    VlTriggerScheduler __VtrigSched_hd1eddec1__0;
    VlTriggerScheduler __VtrigSched_h5ca4dc88__0;

    // INTERNAL VARIABLES
    Vtb_kyber_top__Syms* vlSymsp;
    const char* vlNamep;

    // CONSTRUCTORS
    Vtb_kyber_top___024root(Vtb_kyber_top__Syms* symsp, const char* namep);
    ~Vtb_kyber_top___024root();
    VL_UNCOPYABLE(Vtb_kyber_top___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
